from django.contrib import admin
from Main.models import *


admin.site.register(Info)
admin.site.register(Slider)
admin.site.register(Projects)
admin.site.register(Technopark)
admin.site.register(Section)
admin.site.register(Postalservices)
admin.site.register(Boglanish)
admin.site.register(Mobileoperators)
admin.site.register(Internetproviders)
admin.site.register(OurAudience)
admin.site.register(Percentage)
admin.site.register(Residents)
admin.site.register(Team)
admin.site.register(Coimages)
admin.site.register(Coworking)
admin.site.register(InfrastructureSlider)
admin.site.register(StudyDirections)
admin.site.register(ItAcademy)
admin.site.register(StartupDirections)
admin.site.register(IncubationCenters)
admin.site.register(Raqamlashtirishxizmalari)
admin.site.register(Contact)
admin.site.register(XizmatTuri)
admin.site.register(Xizmatlar)
admin.site.register(Application)
