# Generated by Django 4.0.4 on 2022-06-06 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='text_en',
            field=models.CharField(max_length=2550),
        ),
        migrations.AlterField(
            model_name='section',
            name='text_ru',
            field=models.CharField(max_length=2550),
        ),
        migrations.AlterField(
            model_name='section',
            name='text_uz',
            field=models.CharField(max_length=2550),
        ),
    ]
