# Generated by Django 4.0.4 on 2022-06-08 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_boglanish_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boglanish',
            name='date',
        ),
    ]
